name: Build and Publish Docker Image

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Write value to Properties-file
      uses: christian-draeger/write-properties@1.1.0
      with:
        path: './src/main/resources/application.properties'
        property: |
          'spring.datasource.url'
          'spring.datasource.username'
          'spring.datasource.password'
        value: |
          ${{ secrets.DEV_DB_URL }}
          ${{ secrets.DEV_DB_USERNAME }}
          ${{ secrets.DEV_DB_PASSWORD }}
    - name: Build with Maven
      run: mvn clean install
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       repository: nryan1987/comics
       tags: dev-latest
